
const Home = () => {
  return (
    <div>
      <header className="bg-secondary h-full min-h-screen w-full py-16">
        <div className="mx-auto flex w-[90%] max-w-7xl">
          <div className="mx-auto flex h-1/2 flex-col items-center justify-center text-white">
            <h1 className="text-primary text-4xl font-bold">
              Bring Your Imagination to Life
            </h1>
            <p className="py-4">
              Browse through a collection of imaginative and visually stunning
              images generated by AI.
            </p>

            <form action="submit" className="w-full py-6">
              <label htmlFor="" className="block pb-2">
                Browse Posts
              </label>
              <div className="flex justify-between overflow-hidden rounded bg-white p-2">
                <input type="text" className="text-black" />
                <button className="bg-primary rounded px-4 py-2 hover:opacity-80 focus:opacity-80">
                  Search
                </button>
              </div>
            </form>
          </div>
        </div>
      </header>
    </div>
  );
};

export default Home;
